<?xml version="1.0"?>
<package format="3">
  <name>calculate_mood</name>
  <version>0.0.0</version>
  <description>Calculate mood aggregator package</description>
  <maintainer email="you@example.com">You</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
</package>
