[metadata]
name = calculate_mood
version = 0.0.0
description = Calculate mood aggregator

[options]
packages = find:
install_requires =
    rclpy
    std_msgs
zip_safe = false

[options.entry_points]
console_scripts =
    calculate_mood_dummy = calculate_mood.calculate_mood_dummy:main
    calculate_mood_aggregator = calculate_mood.calculate_mood_aggregator:main
